# Crowdin configuration for Medication Tracker
project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_API_TOKEN

preserve_hierarchy: true

files:
  # Main translation files
  - source: "/translations/messages.pot"
    translation: "/translations/%two_letters_code%/LC_MESSAGES/messages.po"
