services:
  medication-tracker:
    image: skjall/medication-tracker:latest
    container_name: medication-tracker
    ports:
      - '8087:8087'
    volumes:
      - medication_tracker_data:/app/data
      - medication_tracker_logs:/app/logs
    restart: unless-stopped
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY:-change_me_in_production}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    healthcheck:
      test:
        [
          'CMD',
          'python',
          '-c',
          'import urllib.request; urllib.request.urlopen("http://localhost:8087/")',
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  medication_tracker_data:
    name: medication_tracker_data
  medication_tracker_logs:
    name: medication_tracker_logs
