version: '3.8'

services:
  medication-tracker:
    image: ${DOCKER_REGISTRY}/medication-tracker:latest
    container_name: medication-tracker
    ports:
      - '8087:8080'
    volumes:
      - medication_tracker_data:/app/data
    restart: unless-stopped
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY:-change_me_in_production}
    healthcheck:
      test:
        [
          'CMD',
          'wget',
          '--no-verbose',
          '--tries=1',
          '--spider',
          'http://localhost:8080/',
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  medication_tracker_data:
    name: medication_tracker_data
