blank_issues_enabled: true
contact_links:
  - name: Security Vulnerability
    url: https://github.com/skjall/medication-tracker/security/advisories/new
    about: Please report security vulnerabilities privately
  - name: Discussions
    url: https://github.com/skjall/medication-tracker/discussions
    about: Ask questions and discuss ideas with the community