name: 📚 Documentation
description: Suggest improvements or report issues with documentation
title: "[DOCS] "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Help us improve our documentation!
        
  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation issue is this?
      options:
        - Missing documentation
        - Incorrect/outdated documentation
        - Unclear/confusing documentation
        - Typo or formatting issue
        - Request for examples
        - Other
    validations:
      required: true
      
  - type: input
    id: location
    attributes:
      label: Location
      description: Where in the documentation does this issue exist?
      placeholder: "e.g., README.md, /docs/api.md, Installation section"
    validations:
      required: true
      
  - type: textarea
    id: current
    attributes:
      label: Current Documentation
      description: If applicable, quote or describe the current documentation
      placeholder: Copy and paste the current text here
      render: markdown
      
  - type: textarea
    id: suggested
    attributes:
      label: Suggested Improvement
      description: How should the documentation be improved?
      placeholder: Your suggested text or improvement here
      render: markdown
    validations:
      required: true
      
  - type: textarea
    id: reason
    attributes:
      label: Why This Change?
      description: Explain why this change would improve the documentation
      placeholder: This change would help users because...
    validations:
      required: true
      
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any additional information that would help understand the issue or improvement
      
  - type: checkboxes
    id: terms
    attributes:
      label: Confirmation
      options:
        - label: I have checked that this documentation issue hasn't been reported already
          required: true
        - label: I am willing to help update the documentation if needed
          required: false