name: 🚀 Feature Request
description: Suggest an idea for this project
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible.
        
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: "A clear and concise description of what the problem is. Ex: I'm always frustrated when..."
    validations:
      required: true
      
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: true
      
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: List any other ways this could be solved
    validations:
      required: false
      
  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe how this feature would be used in a real-world scenario
      placeholder: |
        - Who would use this feature?
        - When would they use it?
        - What problem does it solve for them?
    validations:
      required: true
      
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical - blocking my use of the application
        - High - would significantly improve my workflow
        - Medium - nice to have
        - Low - minor improvement
    validations:
      required: true
      
  - type: textarea
    id: implementation
    attributes:
      label: Proposed Implementation
      description: If you have ideas about how this could be implemented (optional)
      placeholder: |
        - UI/UX changes needed
        - Database schema changes
        - API endpoints
        - Business logic
        
  - type: textarea
    id: mockups
    attributes:
      label: Mockups or Examples
      description: Add any mockups, diagrams, or examples that help explain the feature. You can paste images directly here.
      
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the feature request here.
      
  - type: checkboxes
    id: terms
    attributes:
      label: Confirmation
      options:
        - label: I have searched the existing issues to ensure this feature has not been requested already
          required: true
        - label: I am willing to help implement this feature if needed
          required: false