"""Add physician model and update medication and visit relationships

Revision ID: 8b5d249f8899
Revises: d578b1d67a33
Create Date: 2025-06-03 22:17:23.932360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b5d249f8899'
down_revision: Union[str, None] = 'd578b1d67a33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('physicians',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('specialty', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('medications', sa.Column('physician_id', sa.Integer(), nullable=True))
    op.add_column('medications', sa.Column('is_otc', sa.Boolean(), nullable=False, server_default='0', comment='True if medication is over-the-counter'))
    op.create_foreign_key(None, 'medications', 'physicians', ['physician_id'], ['id'])
    op.add_column('physician_visits', sa.Column('physician_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'physician_visits', 'physicians', ['physician_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'physician_visits', type_='foreignkey')
    op.drop_column('physician_visits', 'physician_id')
    op.drop_constraint(None, 'medications', type_='foreignkey')
    op.drop_column('medications', 'is_otc')
    op.drop_column('medications', 'physician_id')
    op.drop_table('physicians')
    # ### end Alembic commands ###
