name: Build and Push Docker Image

on:
  push:
    branches: [main, development]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main, development]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest pytest-cov flake8

      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Test with pytest
        run: |
          pytest --cov=app tests/

  build-and-push:
    needs: test
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Custom Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_HOST }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Set Docker tags based on branch
        id: set-tags
        run: |
          # Extract branch name from github.ref (remove 'refs/heads/' prefix)
          BRANCH_NAME=${GITHUB_REF#refs/heads/}

          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "TAGS=${{ secrets.REGISTRY_HOST }}/medication-tracker:latest,${{ secrets.REGISTRY_HOST }}/medication-tracker:$BRANCH_NAME,${{ secrets.REGISTRY_HOST }}/medication-tracker:${{ github.sha }}" >> $GITHUB_OUTPUT
          else
            echo "TAGS=${{ secrets.REGISTRY_HOST }}/medication-tracker:$BRANCH_NAME,${{ secrets.REGISTRY_HOST }}/medication-tracker:${{ github.sha }}" >> $GITHUB_OUTPUT
          fi

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.set-tags.outputs.TAGS }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
